### ISSUE TITLE
Mastodon user is non-existent

### ISSUE THREAD

**Issue by agustux** [dhelonious/mastodon-snap#14]
### Steps to reproduce:
1. `snap install mastodon-server`
2. copy certificate key and CA certs in the mentioned directories from the README
3. `sudo /snap/bin/mastodon-server.setup` # I know this looks messy but this was required to run the script as root like the README
4. `sudo /snap/bin/mastodon-server.tootctl accounts create [owner's username] --email [owner@ownersite.com] --role Owner --confirmed`
5. `sudo -u mastodon RAILS_ENV=production bin/tootctl accounts approve [owner's username]`

### Expected Behavior:
Step 5 should run and finish and a return a success

### Actual Behavior:
```
sudo: unknown user mastodon
sudo: error initializing audit plugin sudoers_audit
```
### Description:
Mastodon has been installed using this snap to the point where an owner account exists but I can't see or post anything because its "application is pending review by our staff". As described in [this](https://github.com/mastodon/mastodon/issues/29380) mastodon issue, the first account should be approved using the `tootctl` tool. However, running that in step 5 shows that the mastodon user wasn't created. What has to be done? I've searched for a bit but there doesn't seem to be relevant documentation on this project about the missing user.

### Mastodon-Snap version:
Latest version available with snap

### OS:
Server hosting the instance is running on Debian 12

**Comment by agustux** [comment]
I'm sorry, I meant to label this as bug not question

**Comment by agustux** [comment]
The tootctl command was used in step 4 so the answer has become obvious

**Comment by dhelonious** [comment]
Glad to hear you were able to solve this problem yourself! I would like to add a brief explanation that might be helpful if anyone else runs into this:

The command `sudo -u mastodon RAILS_ENV=production bin/tootctl` means *run tootctl as user mastodon in production mode*. However, this and similar commands found in the Mastodon documentation or other guides cannot be used directly. Instead, the snap provides `mastodon-server.tootctl` which takes care of everything.

The Mastodon server and most other services run as a dedicated, non-root user within the isolated snap environment. So there is no need to create a user named mastodon on the system.

I have also added an additional note to the Quickstart section of the readme to avoid confusion in the future.
